name: CI

on: [push]

jobs:
  windows_build_and_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.6' # The JDK version to make available on the path.
        java-package: jdk
        architecture: x64
    - uses: ros-tooling/setup-ros@3b3f060
      with:
        required-ros-distributions: dashing
    - uses: jacobperron/action-ros-ci@49adbbe
      with:
        package-name: rosidl_generator_java rcljava_common rcljava
        vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/dashing/ros2.repos
            file://${{ github.workspace }}\ros2_java_desktop.repos
